name: tpot
channels:
  - defaults
dependencies:
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - pytorch
  - joblib
  - notebook
  - tpot
  - matplotlib
  - seaborn
  - gpyopt
  - iprogress
  - ipywidgets
  - jupyter
  - xgboost
